import { type PropertyJavaUseMapper, proxyJavaUse } from '../internal/proxy.js';

const ClassesString = {
    String: 'java.lang.String',
    Boolean: 'java.lang.Boolean',
    ArrayList: 'java.util.ArrayList',
    System: 'java.lang.System',
    Exception: 'java.lang.Exception',
    StringBuilder: 'java.lang.StringBuilder',
    Class: 'java.lang.Class',
    URL: 'java.net.URL',
    Cipher: 'javax.crypto.Cipher',
    SecretKeySpec: 'javax.crypto.spec.SecretKeySpec',
    Object: 'java.lang.Object',
    ClassLoader: 'java.lang.ClassLoader',
    BaseDexClassLoader: 'dalvik.system.BaseDexClassLoader',
    DexClassLoader: 'dalvik.system.DexClassLoader',
    InMemoryDexClassLoader: 'dalvik.system.InMemoryDexClassLoader',
    PathClassLoader: 'dalvik.system.PathClassLoader',
    Date: 'java.util.Date',
    Integer: 'java.lang.Integer',
    Method: 'java.lang.reflect.Method',
    Runtime: 'java.lang.Runtime',
    Map$Entry: 'java.util.Map$Entry',
    Locale: 'java.util.Locale',
    TimeZone: 'java.util.TimeZone',
    Thread: 'java.lang.Thread',
    Arrays: 'java.util.Arrays',
    Math: 'java.lang.Math',
    DexPathList: 'dalvik.system.DexPathList',
    PendingIntent: 'android.app.PendingIntent',
    ZonedDateTime: 'java.time.ZonedDateTime',
    ZoneId: 'java.time.ZoneId',
    Instant: 'java.time.Instant',
    Calendar: 'java.util.Calendar',
    Thread$UncaughtExceptionHandler: 'java.lang.Thread$UncaughtExceptionHandler',
    Application: 'android.app.Application',
    Settings$Secure: 'android.provider.Settings$Secure',
    Settings$Global: 'android.provider.Settings$Global',
    WebView: 'android.webkit.WebView',
    ContentResolver: 'android.content.ContentResolver',
    WebChromeClient: 'android.webkit.WebChromeClient',
    Log: 'android.util.Log',
    JSONObject: 'org.json.JSONObject',
    JSONArray: 'org.json.JSONArray',
    Bundle: 'android.os.Bundle',
    Intent: 'android.content.Intent',
    Activity: 'android.app.Activity',
    SharedPreferences: 'android.content.SharedPreferences',
    SharedPreferencesImpl: 'android.app.SharedPreferencesImpl',
    PackageManager: 'android.content.pm.PackageManager',
    TelephonyManager: 'android.telephony.TelephonyManager',
    Build: 'android.os.Build',
    InstallReferrerClient: 'com.android.installreferrer.api.InstallReferrerClient',
    InstallReferrerStateListener: 'com.android.installreferrer.api.InstallReferrerStateListener',
    ReferrerDetails: 'com.android.installreferrer.api.ReferrerDetails',
    ApplicationPackageManager: 'android.app.ApplicationPackageManager',
    LocationManager: 'android.location.LocationManager',
    Sensor: 'android.hardware.Sensor',
    SystemProperties: 'android.os.SystemProperties',
    Process: 'android.os.Process',
    File: 'java.io.File',
    InetSocketAddress: 'java.net.InetSocketAddress',
    Throwable: 'java.lang.Throwable',
    ActivityManager: 'android.app.ActivityManager',
    ActivityManager$RunningAppProcessInfo: 'android.app.ActivityManager$RunningAppProcessInfo',
    ActivityThread: 'android.app.ActivityThread',
    IoBridge: 'libcore.io.IoBridge',
    Linux: 'libcore.io.Linux',
    ByteArrayInputStream: 'java.io.ByteArrayInputStream',
    StandardCharsets: 'java.nio.charset.StandardCharsets',
    HttpURLConnectionImpl: 'com.android.okhttp.internal.huc.HttpURLConnectionImpl',
    SimpleDateFormat: 'java.text.SimpleDateFormat',
    Resources: 'android.content.res.Resources',
    Preferences: 'androidx.datastore.preferences.core.Preferences',
    Preferences$Key: 'androidx.datastore.preferences.core.Preferences$Key',
    ByteBuffer: 'java.nio.ByteBuffer',
    KeyguardManager: 'android.app.KeyguardManager',
    ContextImpl: 'android.app.ContextImpl',
    Context: 'android.content.Context',
    Executable: 'java.lang.reflect.Executable',
    VMDebug: 'dalvik.system.VMDebug',
    Constructor: 'java.lang.reflect.Constructor',
    DisplayManager: 'android.hardware.display.DisplayManager',
    Signature: 'java.security.Signature',
    MessageDigest: 'java.security.MessageDigest',
};

type ClassesType = PropertyJavaUseMapper<typeof ClassesString>;
const ClassesProxy: ClassesType = proxyJavaUse(ClassesString);

export { ClassesProxy, ClassesString, type ClassesType };
